### PR TITLE
Update of all elements

### PR DESCRIPTION
**Pull request by IamEld3st**

### CODE REVIEW

**Comment by jacksonisiah** [comment]
is this ready to merge?

**Comment by IamEld3st** [comment]
i dont have any additions so i say its ok

**Comment by lvdlee** [comment]
Quality git usage, fix up commit messages first. Give a somewhat accurate idea of what's changed. 'Small fix' says nothing.

**Review by jacksonisiah — APPROVED** [review]
for tayo's sake, the first `Small fixes` commit fixes to puush link instead of local for reasons
second one is just to make the code look prettier I guess

**Comment by cl8n** [comment]
we've decided that we aren't going to be updating the design of this site except for very minor changes where necessary--- keep the work handy though because we can borrow from it for the new site (jackson tells me that he asked you to make these buttons primarily for the new site anyway)

sorry for informing you too late

we'll get the other changes you made in this pr merged in soon

**Pull request closed without merging**
